(** Some utils 
    @author: Phillip Heidegger
*)

(** [first order v1 v2] returns [Some true] with 
    if v1 should be generated before v2 with respect to
    an order [order] (e.g. generated by [get_order]).

    [Some false] is returned if v2 < v1. Otherwise,
    [None] is returned.
*)
val first : 'a list -> 'a -> 'a -> bool option
